import json
import os

base_keys = [
    "arAnimalsExplore", "arAnimalsQuizMode", "arAnimals3dDesc", "arAnimalsView3d", "arAnimalsInstruction",
    "arViewerDragInstruction", "arViewerNoModelTitle", "arViewerComingSoon",
    "arModelNameAt", "arModelNameBalik", "arModelNameCivciv", "arModelNameCicek", "arModelNameDomuz",
    "arModelNameElma", "arModelNameFil", "arModelNameGemi", "arModelNameGunes", "arModelNameHoroz",
    "arModelNameIrgatci", "arModelNameInek", "arModelNameJaguar", "arModelNameKedi", "arModelNameLimon",
    "arModelNameMuz", "arModelNameNar", "arModelNameOrdek", "arModelNamePanda", "arModelNameRobot",
    "arModelNameSincap", "arModelNameSampinyon", "arModelNameTavuk", "arModelNameUzayli", "arModelNameUzum",
    "arModelNameVagon", "arModelNameYildiz", "arModelNameZurafa",
    "arFactAt", "arFactBalik", "arFactCivciv", "arFactDomuz", "arFactKedi", "arFactElma"
]

langs = {
    "ar": {
        "arAnimalsExplore": "اكتشف الحيوانات",
        "arAnimalsQuizMode": "الانتقال إلى وضع الاختبار",
        "arAnimals3dDesc": "اكتشف الحيوانات ثلاثية الأبعاد\nوالعب اختبارًا ممتعًا!",
        "arAnimalsView3d": "عرض ثلاثي الأبعاد →",
        "arAnimalsInstruction": "👆 اسحب للتدوير  •  📦 اضغط على الزر الأيمن السفلي للواقع المعزز",
        "arViewerDragInstruction": "👆 اسحب للتدوير!\n📦 اضغط على الزر الأيمن السفلي لرؤيته في غرفتك.",
        "arViewerNoModelTitle": "لا يوجد نموذج ثلاثي الأبعاد بعد\nللحرف \"{letter}\"",
        "arViewerComingSoon": "قريبًا! 🎉",
        "arModelNameAt": "حصان", "arModelNameBalik": "سمكة", "arModelNameCivciv": "كتكوت",
        "arModelNameCicek": "زهرة", "arModelNameDomuz": "خنزير", "arModelNameElma": "تفاحة",
        "arModelNameFil": "فيل", "arModelNameGemi": "سفينة", "arModelNameGunes": "شمس",
        "arModelNameHoroz": "ديك", "arModelNameIrgatci": "مزارع", "arModelNameInek": "بقرة",
        "arModelNameJaguar": "جاكوار", "arModelNameKedi": "قطة", "arModelNameLimon": "ليمون",
        "arModelNameMuz": "موز", "arModelNameNar": "رمان", "arModelNameOrdek": "بطة",
        "arModelNamePanda": "باندا", "arModelNameRobot": "روبوت", "arModelNameSincap": "سنجاب",
        "arModelNameSampinyon": "فطر", "arModelNameTavuk": "دجاجة", "arModelNameUzayli": "كائن فضائي",
        "arModelNameUzum": "عنب", "arModelNameVagon": "عربة", "arModelNameYildiz": "نجمة",
        "arModelNameZurafa": "زرافة",
        "arFactAt": "يمكن للخيول الركض بسرعة تصل إلى 70 كم/ساعة!",
        "arFactBalik": "يمكن للأسماك التنفس تحت الماء!",
        "arFactCivciv": "يمكن للكتاكيت المشي فور الفقس!",
        "arFactDomuz": "الخنازير حيوانات ذكية جدًا!",
        "arFactKedi": "يمكن للقطط أن تنام لمدة 16 ساعة في اليوم!",
        "arFactElma": "يمكن أن تعيش أشجار التفاح لمدة 100 عام!"
    },
    "az": {
        "arAnimalsExplore": "Heyvanları Kəşf Et",
        "arAnimalsQuizMode": "Viktorina Rejiminə Keç",
        "arAnimals3dDesc": "Heyvanları 3D kəşf et\nvə əyləncəli viktorina oyna!",
        "arAnimalsView3d": "3D Bax →",
        "arAnimalsInstruction": "👆 Fırlatmaq üçün sürüklə  •  📦 AR üçün sağ alt düyməyə bas",
        "arViewerDragInstruction": "👆 Fırlatmaq üçün sürüklə!\n📦 Otağında görmək üçün sağ alt düyməyə bas.",
        "arViewerNoModelTitle": "\"{letter}\" hərfi üçün\nhələ 3D model yoxdur",
        "arViewerComingSoon": "Tezliklə! 🎉",
        "arModelNameAt": "At", "arModelNameBalik": "Balıq", "arModelNameCivciv": "Cücə",
        "arModelNameCicek": "Çiçək", "arModelNameDomuz": "Donuz", "arModelNameElma": "Alma",
        "arModelNameFil": "Fil", "arModelNameGemi": "Gəmi", "arModelNameGunes": "Günəş",
        "arModelNameHoroz": "Xoruz", "arModelNameIrgatci": "Fermer", "arModelNameInek": "İnək",
        "arModelNameJaguar": "Yaquar", "arModelNameKedi": "Pişik", "arModelNameLimon": "Limon",
        "arModelNameMuz": "Banan", "arModelNameNar": "Nar", "arModelNameOrdek": "Ördək",
        "arModelNamePanda": "Panda", "arModelNameRobot": "Robot", "arModelNameSincap": "Dələ",
        "arModelNameSampinyon": "Göbələk", "arModelNameTavuk": "Toyuq", "arModelNameUzayli": "Yadplanetli",
        "arModelNameUzum": "Üzüm", "arModelNameVagon": "Vaqon", "arModelNameYildiz": "Ulduz",
        "arModelNameZurafa": "Zürafə",
        "arFactAt": "Atlar saatda 70 km sürətlə qaça bilər!",
        "arFactBalik": "Balıqlar su altında nəfəs ala bilər!",
        "arFactCivciv": "Cücələr yumurtadan çıxdıqdan dərhal sonra gəzə bilər!",
        "arFactDomuz": "Donuzlar çox ağıllı heyvanlardır!",
        "arFactKedi": "Pişiklər gündə 16 saat yata bilər!",
        "arFactElma": "Alma ağacları 100 il yaşaya bilər!"
    },
    "bn": {
        "arAnimalsExplore": "প্রাণী অন্বেষণ করুন",
        "arAnimalsQuizMode": "কুইজ মোডে যান",
        "arAnimals3dDesc": "3D তে প্রাণী অন্বেষণ করুন\nএবং একটি মজাদার কুইজ খেলুন!",
        "arAnimalsView3d": "3D দেখুন →",
        "arAnimalsInstruction": "👆 ঘোরাতে টেনে আনুন  •  📦 AR-এর জন্য নিচে ডানদিকে বোতাম টিপুন",
        "arViewerDragInstruction": "👆 ঘোরাতে টেনে আনুন!\n📦 আপনার রুমে দেখতে নিচে ডানদিকের বোতাম টিপুন।",
        "arViewerNoModelTitle": "\"{letter}\" অক্ষরের জন্য\nএখনো কোনো 3D মডেল নেই",
        "arViewerComingSoon": "শীঘ্রই আসছে! 🎉",
        "arModelNameAt": "ঘোড়া", "arModelNameBalik": "মাছ", "arModelNameCivciv": "মুরগির বাচ্চা",
        "arModelNameCicek": "ফুল", "arModelNameDomuz": "শূকর", "arModelNameElma": "আপেল",
        "arModelNameFil": "হাতি", "arModelNameGemi": "জাহাজ", "arModelNameGunes": "সূর্য",
        "arModelNameHoroz": "মোরগ", "arModelNameIrgatci": "কৃষক", "arModelNameInek": "গরু",
        "arModelNameJaguar": "জাগুয়ার", "arModelNameKedi": "বিড়াল", "arModelNameLimon": "লেবু",
        "arModelNameMuz": "কলা", "arModelNameNar": "ডালিম", "arModelNameOrdek": "হাঁস",
        "arModelNamePanda": "পান্ডা", "arModelNameRobot": "রোবট", "arModelNameSincap": "কাঠবিড়ালি",
        "arModelNameSampinyon": "মাশরুম", "arModelNameTavuk": "মুরগি", "arModelNameUzayli": "এলিয়েন",
        "arModelNameUzum": "আঙ্গুর", "arModelNameVagon": "ওয়াগন", "arModelNameYildiz": "তারা",
        "arModelNameZurafa": "জিরাফ",
        "arFactAt": "ঘোড়া 70 কিমি/ঘন্টা বেগে দৌড়াতে পারে!",
        "arFactBalik": "মাছ পানির নিচে শ্বাস নিতে পারে!",
        "arFactCivciv": "মুরগির বাচ্চারা ডিম ফোটার সাথে সাথেই হাঁটতে পারে!",
        "arFactDomuz": "শূকর খুব বুদ্ধিমান প্রাণী!",
        "arFactKedi": "বিড়াল দিনে 16 ঘন্টা ঘুমাতে পারে!",
        "arFactElma": "আপেল গাছ 100 বছর বাঁচতে পারে!"
    },
    "de": {
        "arAnimalsExplore": "Tiere entdecken",
        "arAnimalsQuizMode": "Zum Quizmodus",
        "arAnimals3dDesc": "Entdecke Tiere in 3D\nund spiele ein lustiges Quiz!",
        "arAnimalsView3d": "3D ansehen →",
        "arAnimalsInstruction": "👆 Zum Drehen ziehen  •  📦 Für AR unten rechts tippen",
        "arViewerDragInstruction": "👆 Zum Drehen ziehen!\n📦 Tippe unten rechts, um es in deinem Raum zu sehen.",
        "arViewerNoModelTitle": "Noch kein 3D-Modell\nfür den Buchstaben \"{letter}\"",
        "arViewerComingSoon": "Kommt bald! 🎉",
        "arModelNameAt": "Pferd", "arModelNameBalik": "Fisch", "arModelNameCivciv": "Küken",
        "arModelNameCicek": "Blume", "arModelNameDomuz": "Schwein", "arModelNameElma": "Apfel",
        "arModelNameFil": "Elefant", "arModelNameGemi": "Schiff", "arModelNameGunes": "Sonne",
        "arModelNameHoroz": "Hahn", "arModelNameIrgatci": "Bauer", "arModelNameInek": "Kuh",
        "arModelNameJaguar": "Jaguar", "arModelNameKedi": "Katze", "arModelNameLimon": "Zitrone",
        "arModelNameMuz": "Banane", "arModelNameNar": "Granatapfel", "arModelNameOrdek": "Ente",
        "arModelNamePanda": "Panda", "arModelNameRobot": "Roboter", "arModelNameSincap": "Eichhörnchen",
        "arModelNameSampinyon": "Pilz", "arModelNameTavuk": "Huhn", "arModelNameUzayli": "Alien",
        "arModelNameUzum": "Trauben", "arModelNameVagon": "Waggon", "arModelNameYildiz": "Stern",
        "arModelNameZurafa": "Giraffe",
        "arFactAt": "Pferde können bis zu 70 km/h schnell laufen!",
        "arFactBalik": "Fische können unter Wasser atmen!",
        "arFactCivciv": "Küken können sofort nach dem Schlüpfen laufen!",
        "arFactDomuz": "Schweine sind sehr intelligente Tiere!",
        "arFactKedi": "Katzen können 16 Stunden am Tag schlafen!",
        "arFactElma": "Apfelbäume können 100 Jahre alt werden!"
    },
    "es": {
        "arAnimalsExplore": "Explorar Animales",
        "arAnimalsQuizMode": "Modo Prueba",
        "arAnimals3dDesc": "¡Explora animales en 3D\ny juega una prueba divertida!",
        "arAnimalsView3d": "Ver 3D →",
        "arAnimalsInstruction": "👆 Arrastra para rotar  •  📦 Toca abajo a la derecha para AR",
        "arViewerDragInstruction": "👆 ¡Arrastra para rotar!\n📦 Toca abajo a la derecha para verlo en tu cuarto.",
        "arViewerNoModelTitle": "Aún no hay modelo 3D\npara la letra \"{letter}\"",
        "arViewerComingSoon": "¡Próximamente! 🎉",
        "arModelNameAt": "Caballo", "arModelNameBalik": "Pez", "arModelNameCivciv": "Pollito",
        "arModelNameCicek": "Flor", "arModelNameDomuz": "Cerdo", "arModelNameElma": "Manzana",
        "arModelNameFil": "Elefante", "arModelNameGemi": "Barco", "arModelNameGunes": "Sol",
        "arModelNameHoroz": "Gallo", "arModelNameIrgatci": "Granjero", "arModelNameInek": "Vaca",
        "arModelNameJaguar": "Jaguar", "arModelNameKedi": "Gato", "arModelNameLimon": "Limón",
        "arModelNameMuz": "Banana", "arModelNameNar": "Granada", "arModelNameOrdek": "Pato",
        "arModelNamePanda": "Panda", "arModelNameRobot": "Robot", "arModelNameSincap": "Ardilla",
        "arModelNameSampinyon": "Hongo", "arModelNameTavuk": "Gallina", "arModelNameUzayli": "Alienígena",
        "arModelNameUzum": "Uvas", "arModelNameVagon": "Vagón", "arModelNameYildiz": "Estrella",
        "arModelNameZurafa": "Jirafa",
        "arFactAt": "¡Los caballos pueden correr a 70 km/h!",
        "arFactBalik": "¡Los peces respiran bajo el agua!",
        "arFactCivciv": "¡Los pollitos caminan nada más nacer!",
        "arFactDomuz": "¡Los cerdos son muy inteligentes!",
        "arFactKedi": "¡Los gatos pueden dormir 16 horas al día!",
        "arFactElma": "¡Los manzanos pueden vivir 100 años!"
    },
    "fr": {
        "arAnimalsExplore": "Explorer les Animaux",
        "arAnimalsQuizMode": "Passer au Quiz",
        "arAnimals3dDesc": "Explore les animaux en 3D\net joue à un quiz amusant!",
        "arAnimalsView3d": "Voir en 3D →",
        "arAnimalsInstruction": "👆 Glisse pour tourner  •  📦 Touche en bas à droite pour la RA",
        "arViewerDragInstruction": "👆 Glisse pour tourner!\n📦 Touche en bas à droite pour le voir dans ta chambre.",
        "arViewerNoModelTitle": "Pas encore de modèle 3D\npour la lettre \"{letter}\"",
        "arViewerComingSoon": "Bientôt! 🎉",
        "arModelNameAt": "Cheval", "arModelNameBalik": "Poisson", "arModelNameCivciv": "Poussin",
        "arModelNameCicek": "Fleur", "arModelNameDomuz": "Cochon", "arModelNameElma": "Pomme",
        "arModelNameFil": "Éléphant", "arModelNameGemi": "Navire", "arModelNameGunes": "Soleil",
        "arModelNameHoroz": "Coq", "arModelNameIrgatci": "Fermier", "arModelNameInek": "Vache",
        "arModelNameJaguar": "Jaguar", "arModelNameKedi": "Chat", "arModelNameLimon": "Citron",
        "arModelNameMuz": "Banane", "arModelNameNar": "Grenade", "arModelNameOrdek": "Canard",
        "arModelNamePanda": "Panda", "arModelNameRobot": "Robot", "arModelNameSincap": "Écureuil",
        "arModelNameSampinyon": "Champignon", "arModelNameTavuk": "Poule", "arModelNameUzayli": "Extraterrestre",
        "arModelNameUzum": "Raisin", "arModelNameVagon": "Wagon", "arModelNameYildiz": "Étoile",
        "arModelNameZurafa": "Girafe",
        "arFactAt": "Les chevaux peuvent courir jusqu'à 70 km/h !",
        "arFactBalik": "Les poissons peuvent respirer sous l'eau !",
        "arFactCivciv": "Les poussins peuvent marcher juste après l'éclosion !",
        "arFactDomuz": "Les cochons sont très intelligents !",
        "arFactKedi": "Les chats peuvent dormir 16 heures par jour !",
        "arFactElma": "Les pommiers peuvent vivre 100 ans !"
    },
    "hi": {
        "arAnimalsExplore": "जानवरों को खोजें",
        "arAnimalsQuizMode": "प्रश्नोत्तरी मोड",
        "arAnimals3dDesc": "3D में जानवरों को खोजें\nऔर एक मजेदार प्रश्नोत्तरी खेलें!",
        "arAnimalsView3d": "3D देखें →",
        "arAnimalsInstruction": "👆 घुमाने के लिए खींचें  •  📦 AR के लिए नीचे दाईं ओर टैप करें",
        "arViewerDragInstruction": "👆 घुमाने के लिए खींचें!\n📦 इसे अपने कमरे में देखने के लिए नीचे दाईं ओर टैप करें।",
        "arViewerNoModelTitle": "\"{letter}\" अक्षर के लिए\nअभी तक कोई 3D मॉडल नहीं है",
        "arViewerComingSoon": "जल्द आ रहा है! 🎉",
        "arModelNameAt": "घोड़ा", "arModelNameBalik": "मछली", "arModelNameCivciv": "चूजा",
        "arModelNameCicek": "फूल", "arModelNameDomuz": "सुअर", "arModelNameElma": "सेब",
        "arModelNameFil": "हाथी", "arModelNameGemi": "जहाज", "arModelNameGunes": "सूरज",
        "arModelNameHoroz": "मुर्गा", "arModelNameIrgatci": "किसान", "arModelNameInek": "गाय",
        "arModelNameJaguar": "जगुआर", "arModelNameKedi": "बिल्ली", "arModelNameLimon": "नींबू",
        "arModelNameMuz": "केला", "arModelNameNar": "अनार", "arModelNameOrdek": "बत्तख",
        "arModelNamePanda": "पांडा", "arModelNameRobot": "रोबोट", "arModelNameSincap": "गिलहरी",
        "arModelNameSampinyon": "मशरूम", "arModelNameTavuk": "मुर्गी", "arModelNameUzayli": "एलियन",
        "arModelNameUzum": "अंगूर", "arModelNameVagon": "वैगन", "arModelNameYildiz": "तारा",
        "arModelNameZurafa": "जिराफ",
        "arFactAt": "घोड़े 70 किमी/घंटा की रफ्तार से दौड़ सकते हैं!",
        "arFactBalik": "मछलियां पानी के भीतर सांस ले सकती हैं!",
        "arFactCivciv": "चूजे अंडे से निकलते ही चल सकते हैं!",
        "arFactDomuz": "सुअर बहुत बुद्धिमान जानवर हैं!",
        "arFactKedi": "बिल्लियाँ दिन में 16 घंटे सो सकती हैं!",
        "arFactElma": "सेब के पेड़ 100 साल तक जीवित रह सकते हैं!"
    },
    "pt": {
        "arAnimalsExplore": "Explorar Animais",
        "arAnimalsQuizMode": "Modo Quiz",
        "arAnimals3dDesc": "Explore animais em 3D\ne jogue um quiz divertido!",
        "arAnimalsView3d": "Ver 3D →",
        "arAnimalsInstruction": "👆 Arraste para girar  •  📦 Toque no canto inferior direito para AR",
        "arViewerDragInstruction": "👆 Arraste para girar!\n📦 Toque no canto inferior direito para ver no seu quarto.",
        "arViewerNoModelTitle": "Nenhum modelo 3D ainda\npara a letra \"{letter}\"",
        "arViewerComingSoon": "Em breve! 🎉",
        "arModelNameAt": "Cavalo", "arModelNameBalik": "Peixe", "arModelNameCivciv": "Pintinho",
        "arModelNameCicek": "Flor", "arModelNameDomuz": "Porco", "arModelNameElma": "Maçã",
        "arModelNameFil": "Elefante", "arModelNameGemi": "Navio", "arModelNameGunes": "Sol",
        "arModelNameHoroz": "Galo", "arModelNameIrgatci": "Fazendeiro", "arModelNameInek": "Vaca",
        "arModelNameJaguar": "Jaguar", "arModelNameKedi": "Gato", "arModelNameLimon": "Limão",
        "arModelNameMuz": "Banana", "arModelNameNar": "Romã", "arModelNameOrdek": "Pato",
        "arModelNamePanda": "Panda", "arModelNameRobot": "Robô", "arModelNameSincap": "Esquilo",
        "arModelNameSampinyon": "Cogumelo", "arModelNameTavuk": "Galinha", "arModelNameUzayli": "Alienígena",
        "arModelNameUzum": "Uvas", "arModelNameVagon": "Vagão", "arModelNameYildiz": "Estrela",
        "arModelNameZurafa": "Girafa",
        "arFactAt": "Cavalos podem correr até 70 km/h!",
        "arFactBalik": "Os peixes podem respirar debaixo d'água!",
        "arFactCivciv": "Os pintinhos podem andar logo após nascerem!",
        "arFactDomuz": "Porcos são muito inteligentes!",
        "arFactKedi": "Gatos podem dormir 16 horas por dia!",
        "arFactElma": "Macieiras podem viver por 100 anos!"
    },
    "ru": {
        "arAnimalsExplore": "Исследуй Животных",
        "arAnimalsQuizMode": "Режим Викторины",
        "arAnimals3dDesc": "Исследуй животных в 3D\nи играй в веселую викторину!",
        "arAnimalsView3d": "Смотреть 3D →",
        "arAnimalsInstruction": "👆 Вращай пальцем  •  📦 Жми кнопку внизу для AR",
        "arViewerDragInstruction": "👆 Вращай пальцем!\n📦 Нажми кнопку внизу справа, чтобы увидеть в своей комнате.",
        "arViewerNoModelTitle": "Пока нет 3D модели\nдля буквы \"{letter}\"",
        "arViewerComingSoon": "Скоро! 🎉",
        "arModelNameAt": "Лошадь", "arModelNameBalik": "Рыба", "arModelNameCivciv": "Цыпленок",
        "arModelNameCicek": "Цветок", "arModelNameDomuz": "Свинья", "arModelNameElma": "Яблоко",
        "arModelNameFil": "Слон", "arModelNameGemi": "Корабль", "arModelNameGunes": "Солнце",
        "arModelNameHoroz": "Петух", "arModelNameIrgatci": "Фермер", "arModelNameInek": "Корова",
        "arModelNameJaguar": "Ягуар", "arModelNameKedi": "Кот", "arModelNameLimon": "Лимон",
        "arModelNameMuz": "Банан", "arModelNameNar": "Гранат", "arModelNameOrdek": "Утка",
        "arModelNamePanda": "Панда", "arModelNameRobot": "Робот", "arModelNameSincap": "Белка",
        "arModelNameSampinyon": "Гриб", "arModelNameTavuk": "Курица", "arModelNameUzayli": "Пришелец",
        "arModelNameUzum": "Виноград", "arModelNameVagon": "Вагон", "arModelNameYildiz": "Звезда",
        "arModelNameZurafa": "Жираф",
        "arFactAt": "Лошади могут бегать со скоростью до 70 км/ч!",
        "arFactBalik": "Рыбы могут дышать под водой!",
        "arFactCivciv": "Цыплята могут ходить сразу после вылупления!",
        "arFactDomuz": "Свиньи очень умные животные!",
        "arFactKedi": "Кошки могут спать 16 часов в день!",
        "arFactElma": "Яблони могут жить 100 лет!"
    },
    "ur": {
        "arAnimalsExplore": "جانور دریافت کریں",
        "arAnimalsQuizMode": "کوئز موڈ میں جائیں",
        "arAnimals3dDesc": "جانوروں کو 3D میں دریافت کریں\nاور ایک تفریحی کوئز کھیلیں!",
        "arAnimalsView3d": "3D دیکھیں →",
        "arAnimalsInstruction": "👆 گھمانے کے لیے کھینچیں  •  📦 AR کے لیے نیچے دائیں جانب تھپتھپائیں",
        "arViewerDragInstruction": "👆 گھمانے کے لیے کھینچیں!\n📦 اسے اپنے کمرے میں دیکھنے کے لیے نیچے دائیں جانب کا بٹن دبائیں۔",
        "arViewerNoModelTitle": "ابھی تک حرف \"{letter}\" کے لیے\nکوئی 3D ماڈل نہیں ہے",
        "arViewerComingSoon": "جلد آرہا ہے! 🎉",
        "arModelNameAt": "گھوڑا", "arModelNameBalik": "مچھلی", "arModelNameCivciv": "چوزہ",
        "arModelNameCicek": "پھول", "arModelNameDomuz": "سور", "arModelNameElma": "سیب",
        "arModelNameFil": "ہاتھی", "arModelNameGemi": "جہاز", "arModelNameGunes": "سورج",
        "arModelNameHoroz": "مرغا", "arModelNameIrgatci": "کسان", "arModelNameInek": "گائے",
        "arModelNameJaguar": "جیگوار", "arModelNameKedi": "بلی", "arModelNameLimon": "لیمو",
        "arModelNameMuz": "کیلا", "arModelNameNar": "انار", "arModelNameOrdek": "بطخ",
        "arModelNamePanda": "پانڈا", "arModelNameRobot": "روبوٹ", "arModelNameSincap": "گلہری",
        "arModelNameSampinyon": "کھمبی", "arModelNameTavuk": "مرغی", "arModelNameUzayli": "خلائی مخلوق",
        "arModelNameUzum": "انگور", "arModelNameVagon": "ویگن", "arModelNameYildiz": "ستارہ",
        "arModelNameZurafa": "زرافہ",
        "arFactAt": "گھوڑے 70 کلومیٹر فی گھنٹہ کی رفتار سے دوڑ سکتے ہیں!",
        "arFactBalik": "مچھلیاں پانی کے اندر سانس لے سکتی ہیں!",
        "arFactCivciv": "چوزے انڈے سے نکلتے ہی چل سکتے ہیں!",
        "arFactDomuz": "سور بہت ذہین جانور ہیں!",
        "arFactKedi": "بلیاں دن میں 16 گھنٹے سو سکتی ہیں!",
        "arFactElma": "سیب کے درخت 100 سال تک زندہ رہ سکتے ہیں!"
    },
    "zh": {
        "arAnimalsExplore": "探索动物",
        "arAnimalsQuizMode": "切换到问答模式",
        "arAnimals3dDesc": "在3D中探索动物\n并玩有趣的问答游戏！",
        "arAnimalsView3d": "查看 3D →",
        "arAnimalsInstruction": "👆 拖动以旋转  •  📦 点击右下角按钮以使用 AR",
        "arViewerDragInstruction": "👆 拖动以旋转！\n📦 点击右下角按钮在您的房间里查看它。",
        "arViewerNoModelTitle": "还没有字母 \"{letter}\" 的\n3D 模型",
        "arViewerComingSoon": "敬请期待！ 🎉",
        "arModelNameAt": "马", "arModelNameBalik": "鱼", "arModelNameCivciv": "小鸡",
        "arModelNameCicek": "花", "arModelNameDomuz": "猪", "arModelNameElma": "苹果",
        "arModelNameFil": "大象", "arModelNameGemi": "船", "arModelNameGunes": "太阳",
        "arModelNameHoroz": "公鸡", "arModelNameIrgatci": "农民", "arModelNameInek": "牛",
        "arModelNameJaguar": "美洲豹", "arModelNameKedi": "猫", "arModelNameLimon": "柠檬",
        "arModelNameMuz": "香蕉", "arModelNameNar": "石榴", "arModelNameOrdek": "鸭子",
        "arModelNamePanda": "熊猫", "arModelNameRobot": "机器人", "arModelNameSincap": "松鼠",
        "arModelNameSampinyon": "蘑菇", "arModelNameTavuk": "鸡", "arModelNameUzayli": "外星人",
        "arModelNameUzum": "葡萄", "arModelNameVagon": "车厢", "arModelNameYildiz": "星星",
        "arModelNameZurafa": "长颈鹿",
        "arFactAt": "马的奔跑速度可达 70 公里/小时！",
        "arFactBalik": "鱼可以在水下呼吸！",
        "arFactCivciv": "小鸡孵化后可以立即行走！",
        "arFactDomuz": "猪是非常聪明的动物！",
        "arFactKedi": "猫一天可以睡 16 个小时！",
        "arFactElma": "苹果树可以活 100 年！"
    }
}

dir_path = "lib/features/ar/l10n/"
for lang, data in langs.items():
    content = {"@@locale": lang}
    for key, val in data.items():
        content[key] = val
        if key == "arViewerNoModelTitle":
            content["@arViewerNoModelTitle"] = {
                "placeholders": {
                    "letter": {
                        "type": "String",
                        "example": "A"
                    }
                }
            }
    
    with open(dir_path + f"ar_feature_{lang}.arb", "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=2)

print("Generated all ARBs")
