// `flutter gen-l10n` sonrası çalıştırın: `home_localizations.dart` üretilmiş olmalı.
// dart run tool/export_home_string_lookup.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final j = jsonDecode(
    File('lib/features/home/l10n/home_en.arb').readAsStringSync(),
  ) as Map<String, dynamic>;
  final keys = j.keys
      .where((k) => k != '@@locale' && !k.startsWith('@'))
      .cast<String>()
      .toList()
    ..sort();

  final shopKeys =
      keys.where((k) => k.startsWith(RegExp('(hat_|glasses_|outfit_)')));
  final badgeKeys = keys.where(
    (k) => k.startsWith('badge') && (k.endsWith('Name') || k.endsWith('Desc')),
  );

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/export_home_string_lookup.dart\n')
    ..writeln(
      "import 'package:abc123/features/home/l10n/generated/home_localizations.dart';\n",
    )
    ..writeln('String homeShopItemName(HomeLocalizations l, String nameKey) {')
    ..writeln('  switch (nameKey) {');
  for (final k in shopKeys) {
    buf.writeln("    case '$k': return l.$k;");
  }
  buf
    ..writeln('    default: return nameKey;')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('String homeBadgeLine(HomeLocalizations l, String key) {')
    ..writeln('  switch (key) {');
  for (final k in badgeKeys) {
    buf.writeln("    case '$k': return l.$k;");
  }
  buf
    ..writeln('    default: return key;')
    ..writeln('  }')
    ..writeln('}');

  File('lib/features/home/l10n/home_string_lookup.dart')
      .writeAsStringSync(buf.toString());
  stdout.writeln('Wrote lib/features/home/l10n/home_string_lookup.dart');
}
