import json
import os

translations = {
  "az": {
    "colorVisionHomeTitle": "Rəng fiqurları",
    "colorVisionHomeSubtitle": "Əyləncəli skan",
    "colorVisionIntroDisclaimer": "Nöqtəli şəkillər rəngləri necə gördüyünüzü kəşf etməyə kömək edir. Bu tibbi bir test deyil. Narahatlığınız varsa göz həkiminə müraciət edin.",
    "colorVisionStart": "Gəlin oynayaq",
    "colorVisionQuestion": "Nöqtələr arasında hansı fiquru görürsünüz?",
    "colorVisionOptionCircle": "Dairə",
    "colorVisionOptionSquare": "Kvadrat",
    "colorVisionOptionTriangle": "Üçbucaq",
    "colorVisionOptionNothing": "Fiqur yoxdur",
    "colorVisionProgress": "Lövhə {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} doğru eşləşmə",
    "colorVisionResultsTitle": "Tur bitdi!",
    "colorVisionResultsGood": "Fiqurların çoxunu tapdınız — əla!",
    "colorVisionResultsMixed": "Bəzi lövhələr çətin idi; bu uşaqlarda çox yaygındır.",
    "colorVisionResultsLow": "Bir çox fiquru görmək çətin oldu. Bu oyun rəng korluğu diaqnozu qoya bilməz.",
    "colorVisionResultsMedicalNote": "Yalnız öyrənmək və maraq üçündür.",
    "colorVisionPlayAgain": "Yenidən oyna",
    "colorVisionIntroTitle": "Gizli fiqurlar",
    "colorVisionPlateBadgeRg": "Qırmızı · yaşıl",
    "colorVisionPlateBadgeBy": "Mavi · sarı",
    "colorVisionOptionDiamond": "Almaz",
    "colorVisionResultHintTitle": "Əyləncəli xülasə",
    "colorVisionProfileTypical": "Cavablarınız tipik rəng görmə ilə uyğun görünür.",
    "colorVisionProfileRedGreenAxis": "Qırmızı-yaşıl tipli lövhələrdə daha çox çətinlik çəkdiniz.",
    "colorVisionProfileBlueYellowAxis": "Mavi-sarı tipli lövhələrdə daha çox çətinlik çəkdiniz.",
    "colorVisionProfileMixed": "Hər iki növ lövhə çətin idi. Yaxşı işıqda yenidən yoxlayın.",
    "colorVisionProfileInconclusive": "Dəqiq bir nəticə çıxmadı — yenidən yoxlayın.",
    "colorVisionScoreRgLine": "Qırmızı-yaşıl: {correct} / {total}",
    "colorVisionScoreByLine": "Mavi-sarı: {correct} / {total}",
    "colorFailureLoad": "Oyun yüklənmədi. Yenidən cəhd edin.",
    "colorFailurePalette": "Rəng palitrası alınmadı.",
    "colorFailureUnknown": "Gözlənilməz bir xəta baş verdi."
  },
  "de": {
    "colorVisionHomeTitle": "Farbformen",
    "colorVisionHomeSubtitle": "Spaß-Scan",
    "colorVisionIntroDisclaimer": "Punktbilder helfen zu entdecken, wie du Farben siehst. Dies ist kein medizinischer Test. Bei Bedenken wende dich an einen Augenarzt.",
    "colorVisionStart": "Lass uns spielen",
    "colorVisionQuestion": "Welche Form siehst du in den Punkten?",
    "colorVisionOptionCircle": "Kreis",
    "colorVisionOptionSquare": "Quadrat",
    "colorVisionOptionTriangle": "Dreieck",
    "colorVisionOptionNothing": "Keine Form",
    "colorVisionProgress": "Tafel {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} richtige",
    "colorVisionResultsTitle": "Runde beendet!",
    "colorVisionResultsGood": "Du hast die meisten Formen gefunden — toll!",
    "colorVisionResultsMixed": "Einige Tafeln waren knifflig; das ist sehr häufig bei Kindern.",
    "colorVisionResultsLow": "Viele Formen waren schwer zu sehen. Dieses Spiel kann keine Farbenblindheit diagnostizieren.",
    "colorVisionResultsMedicalNote": "Nur zum Lernen und für Neugier; ersetzt keine professionelle Augenpflege.",
    "colorVisionPlayAgain": "Nochmal spielen",
    "colorVisionIntroTitle": "Versteckte Formen",
    "colorVisionPlateBadgeRg": "Rot · Grün",
    "colorVisionPlateBadgeBy": "Blau · Gelb",
    "colorVisionOptionDiamond": "Diamant",
    "colorVisionResultHintTitle": "Zusammenfassung",
    "colorVisionProfileTypical": "Deine Antworten stimmen mit typischem Farbensehen überein.",
    "colorVisionProfileRedGreenAxis": "Du hast mehr der rot-grünen Tafeln verfehlt.",
    "colorVisionProfileBlueYellowAxis": "Du hast mehr der blau-gelben Tafeln verfehlt.",
    "colorVisionProfileMixed": "Beide Arten von Tafeln waren knifflig. Versuche es bei gutem Licht erneut.",
    "colorVisionProfileInconclusive": "Kein klares Muster. Versuche es erneut.",
    "colorVisionScoreRgLine": "Rot-Grün: {correct} / {total}",
    "colorVisionScoreByLine": "Blau-Gelb: {correct} / {total}",
    "colorFailureLoad": "Spiel konnte nicht geladen werden.",
    "colorFailurePalette": "Farbpalette konnte nicht geladen werden.",
    "colorFailureUnknown": "Ein unerwarteter Fehler ist aufgetreten."
  },
  "es": {
    "colorVisionHomeTitle": "Formas de color",
    "colorVisionHomeSubtitle": "Escaneo divertido",
    "colorVisionIntroDisclaimer": "Las imágenes de puntos ayudan a descubrir cómo ves los colores. Esto no es una prueba médica.",
    "colorVisionStart": "Vamos a jugar",
    "colorVisionQuestion": "¿Qué forma ves entre los puntos?",
    "colorVisionOptionCircle": "Círculo",
    "colorVisionOptionSquare": "Cuadrado",
    "colorVisionOptionTriangle": "Triángulo",
    "colorVisionOptionNothing": "Ninguna",
    "colorVisionProgress": "Placa {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} correctas",
    "colorVisionResultsTitle": "¡Ronda terminada!",
    "colorVisionResultsGood": "Encontraste la mayoría de las formas — ¡genial!",
    "colorVisionResultsMixed": "Algunas placas fueron difíciles; esto es común en niños.",
    "colorVisionResultsLow": "Muchas formas fueron difíciles de ver. Este juego no diagnostica daltonismo.",
    "colorVisionResultsMedicalNote": "Solo para aprendizaje y curiosidad.",
    "colorVisionPlayAgain": "Jugar de nuevo",
    "colorVisionIntroTitle": "Formas ocultas",
    "colorVisionPlateBadgeRg": "Rojo · Verde",
    "colorVisionPlateBadgeBy": "Azul · Amarillo",
    "colorVisionOptionDiamond": "Diamante",
    "colorVisionResultHintTitle": "Resumen",
    "colorVisionProfileTypical": "Tus respuestas parecen alinearse con la visión típica de colores.",
    "colorVisionProfileRedGreenAxis": "Fallaste más en las placas de estilo rojo-verde.",
    "colorVisionProfileBlueYellowAxis": "Fallaste más en las placas de estilo azul-amarillo.",
    "colorVisionProfileMixed": "Ambos tipos de placas fueron difíciles. Inténtalo de nuevo con buena luz.",
    "colorVisionProfileInconclusive": "No hay un patrón claro. Inténtalo de nuevo.",
    "colorVisionScoreRgLine": "Rojo-verde: {correct} / {total}",
    "colorVisionScoreByLine": "Azul-amarillo: {correct} / {total}",
    "colorFailureLoad": "No se pudo cargar el juego.",
    "colorFailurePalette": "No se pudo obtener la paleta.",
    "colorFailureUnknown": "Ocurrió un error inesperado."
  },
  "fr": {
    "colorVisionHomeTitle": "Formes de couleurs",
    "colorVisionHomeSubtitle": "Scan amusant",
    "colorVisionIntroDisclaimer": "Les images à points aident à découvrir comment vous voyez les couleurs. Ce n'est pas un test médical.",
    "colorVisionStart": "Allons jouer",
    "colorVisionQuestion": "Quelle forme vois-tu parmi les points ?",
    "colorVisionOptionCircle": "Cercle",
    "colorVisionOptionSquare": "Carré",
    "colorVisionOptionTriangle": "Triangle",
    "colorVisionOptionNothing": "Aucune",
    "colorVisionProgress": "Plaque {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} corrects",
    "colorVisionResultsTitle": "Manche terminée !",
    "colorVisionResultsGood": "Tu as trouvé la plupart des formes — super !",
    "colorVisionResultsMixed": "Certaines plaques étaient difficiles; c'est très commun.",
    "colorVisionResultsLow": "Beaucoup de formes étaient difficiles à voir. Ce jeu ne diagnostique pas le daltonisme.",
    "colorVisionResultsMedicalNote": "Uniquement pour l'apprentissage et la curiosité.",
    "colorVisionPlayAgain": "Rejouer",
    "colorVisionIntroTitle": "Formes cachées",
    "colorVisionPlateBadgeRg": "Rouge · Vert",
    "colorVisionPlateBadgeBy": "Bleu · Jaune",
    "colorVisionOptionDiamond": "Diamant",
    "colorVisionResultHintTitle": "Résumé amusant",
    "colorVisionProfileTypical": "Tes réponses semblent alignées avec une vision des couleurs typique.",
    "colorVisionProfileRedGreenAxis": "Tu as manqué plus de plaques de style rouge-vert.",
    "colorVisionProfileBlueYellowAxis": "Tu as manqué plus de plaques de style bleu-jaune.",
    "colorVisionProfileMixed": "Les deux types étaient difficiles. Réessaie avec une bonne lumière.",
    "colorVisionProfileInconclusive": "Pas de motif clair — réessaie.",
    "colorVisionScoreRgLine": "Rouge-vert: {correct} / {total}",
    "colorVisionScoreByLine": "Bleu-jaune: {correct} / {total}",
    "colorFailureLoad": "Impossible de charger le jeu.",
    "colorFailurePalette": "Impossible d'obtenir la palette.",
    "colorFailureUnknown": "Une erreur s'est produite."
  },
  "pt": {
    "colorVisionHomeTitle": "Formas de cor",
    "colorVisionHomeSubtitle": "Scan divertido",
    "colorVisionIntroDisclaimer": "As imagens de pontos ajudam a descobrir como você vê as cores. Este não é um teste médico.",
    "colorVisionStart": "Vamos jogar",
    "colorVisionQuestion": "Qual forma você vê entre os pontos?",
    "colorVisionOptionCircle": "Círculo",
    "colorVisionOptionSquare": "Quadrado",
    "colorVisionOptionTriangle": "Triângulo",
    "colorVisionOptionNothing": "Nenhuma forma",
    "colorVisionProgress": "Placa {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} corretas",
    "colorVisionResultsTitle": "Rodada terminada!",
    "colorVisionResultsGood": "Você encontrou a maioria das formas — ótimo!",
    "colorVisionResultsMixed": "Algumas placas foram difíceis; isso é comum.",
    "colorVisionResultsLow": "Muitas formas foram difíceis de ver. Este jogo não diagnostica daltonismo.",
    "colorVisionResultsMedicalNote": "Apenas para aprendizado e curiosidade.",
    "colorVisionPlayAgain": "Jogar novamente",
    "colorVisionIntroTitle": "Formas ocultas",
    "colorVisionPlateBadgeRg": "Vermelho · Verde",
    "colorVisionPlateBadgeBy": "Azul · Amarelo",
    "colorVisionOptionDiamond": "Diamante",
    "colorVisionResultHintTitle": "Resumo divertido",
    "colorVisionProfileTypical": "Suas respostas parecem se alinhar com a visão típica.",
    "colorVisionProfileRedGreenAxis": "Você errou mais as placas de estilo vermelho-verde.",
    "colorVisionProfileBlueYellowAxis": "Você errou mais as placas de estilo azul-amarelo.",
    "colorVisionProfileMixed": "Ambos os tipos foram difíceis. Tente novamente com boa luz.",
    "colorVisionProfileInconclusive": "Nenhum padrão claro.",
    "colorVisionScoreRgLine": "Vermelho-verde: {correct} / {total}",
    "colorVisionScoreByLine": "Azul-amarelo: {correct} / {total}",
    "colorFailureLoad": "Falha ao carregar o jogo.",
    "colorFailurePalette": "Não foi possível obter a paleta.",
    "colorFailureUnknown": "Ocorreu um erro."
  },
  "ru": {
    "colorVisionHomeTitle": "Цветовые фигуры",
    "colorVisionHomeSubtitle": "Веселое сканирование",
    "colorVisionIntroDisclaimer": "Точечные картинки помогут узнать, как вы видите цвета. Это не медицинский тест.",
    "colorVisionStart": "Давай играть",
    "colorVisionQuestion": "Какую фигуру ты видишь среди точек?",
    "colorVisionOptionCircle": "Круг",
    "colorVisionOptionSquare": "Квадрат",
    "colorVisionOptionTriangle": "Треугольник",
    "colorVisionOptionNothing": "Никакой",
    "colorVisionProgress": "Картинка {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} правильных",
    "colorVisionResultsTitle": "Раунд завершен!",
    "colorVisionResultsGood": "Ты нашел большинство фигур — отлично!",
    "colorVisionResultsMixed": "Некоторые картинки были сложными; это часто бывает у детей.",
    "colorVisionResultsLow": "Многие фигуры было трудно разглядеть. Эта игра не ставит диагноз.",
    "colorVisionResultsMedicalNote": "Только для обучения и любопытства.",
    "colorVisionPlayAgain": "Играть снова",
    "colorVisionIntroTitle": "Скрытые фигуры",
    "colorVisionPlateBadgeRg": "Красный · Зеленый",
    "colorVisionPlateBadgeBy": "Синий · Желтый",
    "colorVisionOptionDiamond": "Ромб",
    "colorVisionResultHintTitle": "Веселое резюме",
    "colorVisionProfileTypical": "Твои ответы совпадают с типичным цветовым зрением.",
    "colorVisionProfileRedGreenAxis": "Ты пропустил больше картинок красно-зеленого стиля.",
    "colorVisionProfileBlueYellowAxis": "Ты пропустил больше картинок сине-желтого стиля.",
    "colorVisionProfileMixed": "Оба типа картинок были сложными. Попробуй еще раз при хорошем освещении.",
    "colorVisionProfileInconclusive": "Нет четкой картины — попробуй еще раз.",
    "colorVisionScoreRgLine": "Красно-зеленый: {correct} / {total}",
    "colorVisionScoreByLine": "Сине-желтый: {correct} / {total}",
    "colorFailureLoad": "Не удалось загрузить игру.",
    "colorFailurePalette": "Не удалось получить палитру.",
    "colorFailureUnknown": "Произошла ошибка."
  },
  "ar": {
    "colorVisionHomeTitle": "أشكال الألوان",
    "colorVisionHomeSubtitle": "مسح ممتع",
    "colorVisionIntroDisclaimer": "تساعدك صور النقاط على اكتشاف كيفية رؤيتك للألوان. هذا ليس اختبارًا طبيًا.",
    "colorVisionStart": "هيا نلعب",
    "colorVisionQuestion": "ما الشكل الذي تراه بين النقاط؟",
    "colorVisionOptionCircle": "دائرة",
    "colorVisionOptionSquare": "مربع",
    "colorVisionOptionTriangle": "مثلث",
    "colorVisionOptionNothing": "لا يوجد شكل",
    "colorVisionProgress": "لوحة {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} صحيح",
    "colorVisionResultsTitle": "انتهت الجولة!",
    "colorVisionResultsGood": "لقد وجدت معظم الأشكال — رائع!",
    "colorVisionResultsMixed": "كانت بعض اللوحات صعبة؛ هذا شائع جدًا عند الأطفال.",
    "colorVisionResultsLow": "كان من الصعب رؤية العديد من الأشكال. هذه اللعبة لا تشخص عمى الألوان.",
    "colorVisionResultsMedicalNote": "للتعلم والفضول فقط.",
    "colorVisionPlayAgain": "العب مرة أخرى",
    "colorVisionIntroTitle": "أشكال مخفية",
    "colorVisionPlateBadgeRg": "أحمر · أخضر",
    "colorVisionPlateBadgeBy": "أزرق · أصفر",
    "colorVisionOptionDiamond": "ماسة",
    "colorVisionResultHintTitle": "ملخص ممتع",
    "colorVisionProfileTypical": "يبدو أن إجاباتك تتماشى مع الرؤية النموذجية للألوان.",
    "colorVisionProfileRedGreenAxis": "لقد فاتتك المزيد من لوحات النمط الأحمر والأخضر.",
    "colorVisionProfileBlueYellowAxis": "لقد فاتتك المزيد من لوحات النمط الأزرق والأصفر.",
    "colorVisionProfileMixed": "كان كلا النوعين من اللوحات صعبًا. حاول مرة أخرى في ضوء جيد.",
    "colorVisionProfileInconclusive": "لا يوجد نمط واضح — حاول مرة أخرى.",
    "colorVisionScoreRgLine": "النمط الأحمر والأخضر: {correct} / {total}",
    "colorVisionScoreByLine": "النمط الأزرق والأصفر: {correct} / {total}",
    "colorFailureLoad": "فشل تحميل اللعبة.",
    "colorFailurePalette": "تعذر جلب لوحة الألوان.",
    "colorFailureUnknown": "حدث خطأ غير متوقع."
  },
  "hi": {
    "colorVisionHomeTitle": "रंग आकृतियाँ",
    "colorVisionHomeSubtitle": "मज़ेदार स्कैन",
    "colorVisionIntroDisclaimer": "डॉट चित्र यह जानने में मदद करते हैं कि आप रंग कैसे देखते हैं। यह कोई चिकित्सा परीक्षण नहीं है।",
    "colorVisionStart": "चलो खेलें",
    "colorVisionQuestion": "बिंदुओं के बीच आप कौन सी आकृति देखते हैं?",
    "colorVisionOptionCircle": "वृत्त",
    "colorVisionOptionSquare": "वर्ग",
    "colorVisionOptionTriangle": "त्रिभुज",
    "colorVisionOptionNothing": "कोई आकृति नहीं",
    "colorVisionProgress": "प्लेट {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} सही",
    "colorVisionResultsTitle": "राउंड समाप्त!",
    "colorVisionResultsGood": "आपको अधिकांश आकृतियाँ मिल गईं — बढ़िया!",
    "colorVisionResultsMixed": "कुछ प्लेटें कठिन थीं; यह बच्चों में बहुत आम है।",
    "colorVisionResultsLow": "कई आकृतियों को देखना कठिन था। यह खेल रंग अंधापन का निदान नहीं कर सकता।",
    "colorVisionResultsMedicalNote": "केवल सीखने और जिज्ञासा के लिए।",
    "colorVisionPlayAgain": "फिर से खेलें",
    "colorVisionIntroTitle": "छिपी हुई आकृतियाँ",
    "colorVisionPlateBadgeRg": "लाल · हरा",
    "colorVisionPlateBadgeBy": "नीला · पीला",
    "colorVisionOptionDiamond": "हीरा",
    "colorVisionResultHintTitle": "मज़ेदार सारांश",
    "colorVisionProfileTypical": "आपके उत्तर सामान्य रंग दृष्टि के अनुरूप प्रतीत होते हैं।",
    "colorVisionProfileRedGreenAxis": "आपसे लाल-हरी शैली की अधिक प्लेटें छूट गईं।",
    "colorVisionProfileBlueYellowAxis": "आपसे नीली-पीली शैली की अधिक प्लेटें छूट गईं।",
    "colorVisionProfileMixed": "दोनों प्रकार की प्लेटें कठिन थीं। अच्छी रोशनी में फिर से प्रयास करें।",
    "colorVisionProfileInconclusive": "कोई स्पष्ट पैटर्न नहीं — फिर से प्रयास करें।",
    "colorVisionScoreRgLine": "लाल-हरा: {correct} / {total}",
    "colorVisionScoreByLine": "नीला-पीला: {correct} / {total}",
    "colorFailureLoad": "गेम लोड करने में विफल।",
    "colorFailurePalette": "रंग पैलेट प्राप्त नहीं किया जा सका।",
    "colorFailureUnknown": "एक अप्रत्याशित त्रुटि हुई।"
  },
  "zh": {
    "colorVisionHomeTitle": "颜色形状",
    "colorVisionHomeSubtitle": "有趣的扫描",
    "colorVisionIntroDisclaimer": "圆点图片帮助您发现您是如何看待颜色的。这不是医学测试。",
    "colorVisionStart": "开始游戏",
    "colorVisionQuestion": "你在圆点中看到了什么形状？",
    "colorVisionOptionCircle": "圆形",
    "colorVisionOptionSquare": "正方形",
    "colorVisionOptionTriangle": "三角形",
    "colorVisionOptionNothing": "没有形状",
    "colorVisionProgress": "图片 {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} 正确",
    "colorVisionResultsTitle": "回合结束！",
    "colorVisionResultsGood": "你找到了大多数形状 — 太棒了！",
    "colorVisionResultsMixed": "有些图片比较难；这在孩子中很常见。",
    "colorVisionResultsLow": "许多形状很难看清。这个游戏不能诊断色盲。",
    "colorVisionResultsMedicalNote": "仅供学习和好奇。",
    "colorVisionPlayAgain": "再玩一次",
    "colorVisionIntroTitle": "隐藏的形状",
    "colorVisionPlateBadgeRg": "红 · 绿",
    "colorVisionPlateBadgeBy": "蓝 · 黄",
    "colorVisionOptionDiamond": "菱形",
    "colorVisionResultHintTitle": "有趣的小结",
    "colorVisionProfileTypical": "你的答案似乎与典型的颜色视觉一致。",
    "colorVisionProfileRedGreenAxis": "你错过了更多红绿风格的图片。",
    "colorVisionProfileBlueYellowAxis": "你错过了更多蓝黄风格的图片。",
    "colorVisionProfileMixed": "两种类型的图片都有点难。请在光线好的地方再试一次。",
    "colorVisionProfileInconclusive": "没有明显的规律 — 请重试。",
    "colorVisionScoreRgLine": "红绿色盲图: {correct} / {total}",
    "colorVisionScoreByLine": "蓝黄色盲图: {correct} / {total}",
    "colorFailureLoad": "游戏加载失败。",
    "colorFailurePalette": "无法获取颜色调色板。",
    "colorFailureUnknown": "发生未知错误。"
  },
  "bn": {
    "colorVisionHomeTitle": "রঙের আকার",
    "colorVisionHomeSubtitle": "মজার স্ক্যান",
    "colorVisionIntroDisclaimer": "বিন্দু ছবি আপনাকে আবিষ্কার করতে সাহায্য করে আপনি কীভাবে রঙ দেখেন। এটি কোনো চিকিৎসা পরীক্ষা নয়।",
    "colorVisionStart": "চলো খেলি",
    "colorVisionQuestion": "বিন্দুগুলির মধ্যে আপনি কোন আকার দেখতে পান?",
    "colorVisionOptionCircle": "বৃত্ত",
    "colorVisionOptionSquare": "বর্গক্ষেত্র",
    "colorVisionOptionTriangle": "ত্রিভুজ",
    "colorVisionOptionNothing": "কোন আকার নেই",
    "colorVisionProgress": "প্লেট {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} সঠিক",
    "colorVisionResultsTitle": "রাউন্ড শেষ!",
    "colorVisionResultsGood": "আপনি বেশিরভাগ আকার খুঁজে পেয়েছেন — দারুণ!",
    "colorVisionResultsMixed": "কিছু প্লেট কঠিন ছিল; এটি শিশুদের মধ্যে খুব সাধারণ।",
    "colorVisionResultsLow": "অনেক আকার দেখতে কঠিন ছিল। এই গেমটি বর্ণান্ধতা নির্ণয় করতে পারে না।",
    "colorVisionResultsMedicalNote": "শুধুমাত্র শেখার এবং কৌতূহলের জন্য।",
    "colorVisionPlayAgain": "আবার খেলুন",
    "colorVisionIntroTitle": "লুকানো আকার",
    "colorVisionPlateBadgeRg": "লাল · সবুজ",
    "colorVisionPlateBadgeBy": "নীল · হলুদ",
    "colorVisionOptionDiamond": "হীরা",
    "colorVisionResultHintTitle": "মজার সারসংক্ষেপ",
    "colorVisionProfileTypical": "আপনার উত্তরগুলি সাধারণত রঙের দর্শনের সাথে সামঞ্জস্যপূর্ণ বলে মনে হচ্ছে।",
    "colorVisionProfileRedGreenAxis": "আপনি লাল-সবুজ শৈলীর প্লেটগুলি বেশি মিস করেছেন।",
    "colorVisionProfileBlueYellowAxis": "আপনি নীল-হলুদ শৈলীর প্লেটগুলি বেশি মিস করেছেন।",
    "colorVisionProfileMixed": "উভয় ধরনের প্লেট কঠিন ছিল। ভালো আলোতে আবার চেষ্টা করুন।",
    "colorVisionProfileInconclusive": "কোনো স্পষ্ট প্যাটার্ন নেই — আবার চেষ্টা করুন।",
    "colorVisionScoreRgLine": "লাল-সবুজ: {correct} / {total}",
    "colorVisionScoreByLine": "নীল-হলুদ: {correct} / {total}",
    "colorFailureLoad": "গেম লোড করতে ব্যর্থ।",
    "colorFailurePalette": "রঙের প্যালেট আনা যায়নি।",
    "colorFailureUnknown": "অপ্রত্যাশিত ত্রুটি ঘটেছে।"
  },
  "ur": {
    "colorVisionHomeTitle": "رنگوں کی اشکال",
    "colorVisionHomeSubtitle": "مزے دار اسکین",
    "colorVisionIntroDisclaimer": "نقطوں والی تصاویر سے پتہ چلتا ہے کہ آپ رنگ کیسے دیکھتے ہیں۔ یہ کوئی طبی ٹیسٹ نہیں ہے۔",
    "colorVisionStart": "آئیں کھیلیں",
    "colorVisionQuestion": "آپ کو نقطوں کے درمیان کون سی شکل نظر آتی ہے؟",
    "colorVisionOptionCircle": "دائرہ",
    "colorVisionOptionSquare": "مربع",
    "colorVisionOptionTriangle": "مثلث",
    "colorVisionOptionNothing": "کوئی شکل نہیں",
    "colorVisionProgress": "پلیٹ {current} / {total}",
    "colorVisionScoreLine": "{correct} / {total} درست",
    "colorVisionResultsTitle": "راؤنڈ ختم!",
    "colorVisionResultsGood": "آپ نے زیادہ تر اشکال تلاش کر لیں — زبردست!",
    "colorVisionResultsMixed": "کچھ پلیٹیں مشکل تھیں؛ بچوں میں یہ بہت عام ہے۔",
    "colorVisionResultsLow": "بہت سی اشکال دیکھنا مشکل تھا۔ یہ گیم کلر بلائنڈنس کی تشخیص نہیں کر سکتی۔",
    "colorVisionResultsMedicalNote": "صرف سیکھنے اور تجسس کے لیے۔",
    "colorVisionPlayAgain": "دوبارہ کھیلیں",
    "colorVisionIntroTitle": "چھپی ہوئی اشکال",
    "colorVisionPlateBadgeRg": "سرخ · سبز",
    "colorVisionPlateBadgeBy": "نیلا · پیلا",
    "colorVisionOptionDiamond": "ہیرا",
    "colorVisionResultHintTitle": "مزے دار خلاصہ",
    "colorVisionProfileTypical": "آپ کے جوابات عام رنگ کی بصارت کے مطابق ہیں۔",
    "colorVisionProfileRedGreenAxis": "آپ نے سرخ-سبز قسم کی پلیٹیں زیادہ چھوڑ دیں۔",
    "colorVisionProfileBlueYellowAxis": "آپ نے نیلی-پیلی قسم کی پلیٹیں زیادہ چھوڑ دیں۔",
    "colorVisionProfileMixed": "دونوں قسم کی پلیٹیں مشکل تھیں۔ اچھی روشنی میں دوبارہ کوشش کریں۔",
    "colorVisionProfileInconclusive": "کوئی واضح پیٹرن نہیں — دوبارہ کوشش کریں۔",
    "colorVisionScoreRgLine": "سرخ-سبز: {correct} / {total}",
    "colorVisionScoreByLine": "نیلا-پیلا: {correct} / {total}",
    "colorFailureLoad": "گیم لوڈ کرنے میں ناکام۔",
    "colorFailurePalette": "رنگوں کا پیلیٹ حاصل نہیں کیا جا سکا۔",
    "colorFailureUnknown": "ایک غیر متوقع خربی پیش آگئی۔"
  }
}

arb_dir = 'lib/features/colors/l10n'

for loc, trans in translations.items():
    file_path = os.path.join(arb_dir, f'colors_{loc}.arb')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Update existing data with new translations
        for key, value in trans.items():
            data[key] = value
            
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated colors_{loc}.arb")

